repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files


  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.2
    hooks:
      # Run the Ruff formatter.
      - id: ruff-format


  - repo: local
    hooks:
      - id: mypy
        name: mypy - Static type checking
        description: Mypy helps ensure that we use our functions and variables correctly by checking the types.
        entry: mypy
        language: system
        types: [python]
        exclude: ^examples/
        require_serial: true
